### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by kinsung** [bgin/MissileSimulation#1]
This project seems to be awesome. How to use this library? I am very confused. 
Can you provide some example?

**Comment by bgin** [comment]
Hi kinsung,

Thank you for expressing your interest in my project.

This project is kept currently on hold.
As you may see project's repository holds only source files.
If you are interested you can freely grab what you need.

I plan continuation of the development work in the foreseeable future.
The most important part of the simulation is proper modeling
of the Radar and guidance system.
Those parts are most challenging ones to implement, beside that
a lot of code shall be rewritten/redesigned from the scratch in order
to boost a performance.

P.s.
        If you are interested in radar simulation you may have a look
        at two additional projects(C++,Fortran) which are pinned
(Atmosphere modeling).

Best regards

Bernard





"*If I have seen further, it is by standing on the shoulders of giants*."
-- Isaac Newton 1676.

*"Science is Truth for life and in Fortran tongue the Answer."*

**Comment by kinsung** [comment]
Thank you for your reply to my question.

As you pointed out, correct modeling is the most critical and difficult task. I quite agree with you.

I want to do an air war game, I will pay attention to your work, but I am just an ordinary software developer, and I cannot understand your project and the complex mathematical models in it at present. Hopefully in the future, you'll provide some tutorials.

Thank you again!

**Comment by bgin** [comment]
Hi kinsung,

This simulation will not run in real-time. As matter of fact just
calculation of  flight dynamics
is implemented by calls to F77 Integrator DVODE which is time consuming
operation.

In "air war game" what kind of details you attempt to model?
IMHO you will need at least 6-DOF simulation, but at expense of realistic
guidance and
aircraft/missile sensor modeling.
In most games (real-time) modeling an atmosphere is based on simplistic
models
like https://omniweb.gsfc.nasa.gov/vitmo/msis_vitmo.html
I tend to rely upon WRF modules which are CPU and memory hungry.

Now regarding your project  you may have a look at "FlightGear" simulation.

Good luck

Bernard Gingold


"*If I have seen further, it is by standing on the shoulders of giants*."
-- Isaac Newton 1676.

*"Science is Truth for life and in Fortran tongue the Answer."*
